// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU2V92GkibvfNsgmUGxXlDqRhTGgAEYEg',
    appId: '1:730698076961:web:ede83c40fdc571f4b52460',
    messagingSenderId: '730698076961',
    projectId: 'app-db-a9755',
    authDomain: 'app-db-a9755.firebaseapp.com',
    storageBucket: 'app-db-a9755.firebasestorage.app',
    measurementId: 'G-F81KBBK9KC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf-zbMEJ95bEi2AxpCqrEXinz6TCUfwWs',
    appId: '1:730698076961:android:bf29c1b30ba0a4f9b52460',
    messagingSenderId: '730698076961',
    projectId: 'app-db-a9755',
    storageBucket: 'app-db-a9755.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAfqCMjYyHLN-LjrGsvjUkbBXt2rS6534',
    appId: '1:730698076961:ios:0f20b46c858c38c5b52460',
    messagingSenderId: '730698076961',
    projectId: 'app-db-a9755',
    storageBucket: 'app-db-a9755.firebasestorage.app',
    iosClientId: '730698076961-2gkiui81qjkem1t8e1mvns7oqqiedg63.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAfqCMjYyHLN-LjrGsvjUkbBXt2rS6534',
    appId: '1:730698076961:ios:0f20b46c858c38c5b52460',
    messagingSenderId: '730698076961',
    projectId: 'app-db-a9755',
    storageBucket: 'app-db-a9755.firebasestorage.app',
    iosClientId: '730698076961-2gkiui81qjkem1t8e1mvns7oqqiedg63.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU2V92GkibvfNsgmUGxXlDqRhTGgAEYEg',
    appId: '1:730698076961:web:63fbd55f446a355eb52460',
    messagingSenderId: '730698076961',
    projectId: 'app-db-a9755',
    authDomain: 'app-db-a9755.firebaseapp.com',
    storageBucket: 'app-db-a9755.firebasestorage.app',
    measurementId: 'G-JF6HCLCMP2',
  );
}
